# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.17.1

# User
debian_user_name: pearl
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEDnben/dwVnDdzc0hJqGpZsEbb9r4HyFTajVIY/Ig1o pearl@indexer.media.tinynamoo.me"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Pearl] Prowlarr/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Pearl] Prowlarr/user.keytab"

# NFS
nfs_user_name: prowlarr
nfs_user_id: 286
nfs_mounts:
  marilyn-configs-prowlarr:
    mount_share: marilyn-configs-prowlarr
    mount_point: /srv/marilyn-configs-prowlarr
  marilyn-databases-prowlarr:
    mount_share: marilyn-databases-prowlarr
    mount_point: /srv/marilyn-databases-prowlarr

## NGINX variables
nginx_conf_files:
  - filename: prowlarr.conf
    path: templates/nginx.prowlarr.conf

## Prowlarr variables
prowlarr_media_group_name: media
prowlarr_media_group_gid: 200

prowlarr_docker_name: prowlarr
flaresolverr_docker_name: flaresolverr

## Proxmox variables
proxmox_snapshot_vmid: 17114
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: prowlarr
docker_project_src: /opt/prowlarr
