# @format

# Uptime Kuma
# Backup the Uptime kuma data directory.
---
- name: Backup uptime kuma data directory
  become: true
  block:
    - name: Ensure rsync is installed
      ansible.builtin.apt:
        name: rsync
        update_cache: true
        state: present

    - name: Ensure uptime kuma docker containers are stopped
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: absent

    - name: Sync data directory from local application directory to NFS server
      ansible.posix.synchronize:
        src: "{{ docker_project_src }}/data"
        dest: "{{ nfs_mounts.serene.mount_point }}/"
        owner: false
        group: false
      delegate_to: "{{ inventory_hostname }}"

    - name: Start uptime kuma docker containers
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: present
      when: "'backup' in ansible_run_tags"
