# @format

# Uptime Kuma
# Upgrade Uptime Kuma monitoring tool
---
- name: Check if uptime kuma requires update
  become: true
  block:
    - name: Get latest uptime kuma container release from github
      become: false
      community.general.github_release:
        user: louislam
        repo: uptime-kuma
        action: latest_release
      delegate_to: localhost
      register: kuma_github_release

    - name: Extract latest uptime kuma container version
      ansible.builtin.set_fact:
        kuma_latest_version: "{{ kuma_github_release.tag }}"

    - name: Fix application docker image versionings in fact
      ansible.builtin.set_fact:
        kuma_latest_version: "v{{ kuma_latest_version }}"

    - name: Stop play if miniflux has no updates
      ansible.builtin.meta: end_play
      when: kuma_image_version == kuma_latest_version

- name: Take snapshot of Proxmox instance
  ansible.builtin.import_role:
    name: proxmox
    public: false
  vars:
    proxmox_task_list: snapshot
    proxmox_snapshot_name: "{{ 'pre_upgrade_uptime_kuma_' + (kuma_latest_version | regex_replace('[.]', '-')) }}"
    proxmox_snapshot_description: "[Ansible] Working snapshot of uptime kuma {{ kuma_image_version }} before upgrading to {{ kuma_latest_version }}"
  delegate_to: localhost

- name: Backup uptime kuma data directory
  ansible.builtin.import_tasks: backup.yaml

- name: Ensure docker-compose file is updated
  become: true
  ansible.builtin.template:
    src: templates/app.docker-compose.yaml
    dest: "{{ docker_project_src }}/docker-compose.yaml"
    owner: "{{ nfs_user_name }}"
    group: "{{ nfs_user_name }}"
    mode: "0640"

- name: Upgrade uptime kuma monitoring tool
  become: true
  block:
    - name: Update apt cache, upgrade packages and remove unused dependencies
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        purge: true

    - name: Update & start uptime kuma docker containers
      become: true
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        remove_orphans: true
        pull: always
        state: present

    - name: Prune unused docker objects
      community.docker.docker_prune:
        builder_cache_all: true
        containers: true
        images: true
        networks: true
        volumes: true
