# @format

# Sonarr
# Install and configure the Sonarr TV managment server.
---
- name: Setup Sonarr application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: /opt/sonarr
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: /opt/sonarr/docker-compose.yaml
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

- name: Setup sonarr user
  become: true
  block:
    - name: Create media group
      ansible.builtin.group:
        name: "{{ sonarr_media_group_name }}"
        gid: "{{ sonarr_media_group_gid }}"
        system: true
        state: present

    - name: Add sonarr user to media group
      ansible.builtin.user:
        name: "{{ nfs_user_name }}"
        groups: "{{ sonarr_media_group_name }}"
        append: true

- name: Setup recyclarr configuration
  become: true
  ansible.builtin.template:
    src: templates/app.recyclarr.yaml
    dest: "{{ nfs_mounts.marilyn.mount_point }}/configs/recyclarr/sonarr/recyclarr.yaml"
    owner: "{{ nfs_user_name }}"
    group: "media"
    mode: "0640"

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
      - "{{ sonarr_4k_hostname }}"
      - "{{ sonarr_anime_hostname }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start sonarr docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: sonarr
    project_src: /opt/sonarr
    state: present
