# @format

# Sonarr
# Configure & manage Sonarr TV management server.
---
- name: Configure & manage Sonarr TV management server
  hosts: sonarr

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        task_list:
          - docker

  tasks:
    - name: Install and configure the Sonarr TV managment server
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade Sonarr TV management server
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
