# @format

# Sonarr
# Upgrade Sonarr TV management server
---
- name: Check if sonarr requires update
  become: true
  block:
    - name: Get current sonarr container version
      ansible.builtin.import_role:
        name: docker
        public: false
      vars:
        docker_task_list: get_container_image_version
        docker_container_name: "{{ sonarr_docker_name }}"
        docker_fact_name: sonarr

    - name: Get latest sonarr container release from github
      community.general.github_release:
        user: linuxserver
        repo: docker-sonarr
        action: latest_release
      delegate_to: localhost
      register: sonarr_github_release

    - name: Extract latest sonarr container version
      ansible.builtin.set_fact:
        sonarr_latest_version: "{{ sonarr_github_release.tag }}"

    - name: Stop play if sonarr has no updates
      ansible.builtin.meta: end_play
      when: sonarr_image_version == sonarr_latest_version

- name: Take snapshot of Proxmox instance
  ansible.builtin.import_role:
    name: proxmox
    public: false
  vars:
    proxmox_task_list: snapshot
    proxmox_snapshot_name: "{{ 'pre_upgrade_sonarr-' + (sonarr_image_version | regex_replace('[.]', '-')) }}"
    proxmox_snapshot_description: "[Ansible] Working snapshot of sonarr {{ sonarr_image_version }} before upgrading to {{ sonarr_latest_version }}"
  delegate_to: localhost

- name: Upgrade Sonarr TV management server
  become: true
  block:
    - name: Update apt cache, upgrade packages and remove unused dependencies
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        purge: true

    - name: Update & start Sonarr docker containers
      become: true
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        remove_orphans: true
        services:
          - "{{ sonarr_docker_name }}"
          - "{{ sonarr_docker_name }}4k"
          - "{{ sonarr_docker_name }}-anime"
          - postgres
        pull: always
        state: present

    - name: Prune unused docker objects
      community.docker.docker_prune:
        builder_cache_all: true
        containers: true
        images: true
        networks: true
        volumes: true
