# @format

# Ntfy
# Backup the Ntfy notifications cache & data directory.
---
- name: Backup ntfy cache & data directories
  become: true
  block:
    - name: Ensure rsync is installed
      ansible.builtin.apt:
        name: rsync
        update_cache: true
        state: present

    - name: Ensure ntfy docker containers are stopped
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: absent

    - name: Sync cache & data directories from local application directory to NFS server
      ansible.posix.synchronize:
        src: "{{ docker_project_src }}/{{ item }}"
        dest: "{{ nfs_mounts.karina.mount_point }}/"
        owner: false
        group: false
      delegate_to: "{{ inventory_hostname }}"
      loop:
        - cache
        - data

    - name: Start ntfy docker containers
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: present
