# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: sakura
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMAVgcaHWq+24aLg0KijJ+/5AWqc1eJd6gypW9shHQR sakura@games.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Sakura] Gamevault/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Sakura] Gamevault/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['gamevault'].name }}"
nfs_user_id: "{{ nfs_clients['gamevault'].uid }}"
nfs_mounts:
  sakura:
    mount_share: /sakura
    mount_point: /srv/sakura

## NGINX variables
nginx_conf_files:
  - filename: gamevault.conf
    path: templates/nginx.gamevault.conf

## Gamevault variables
gamevault_docker_name: gamevault

gamevault_image_version: v13.1.3

## Proxmox variables
proxmox_snapshot_vmid: 20230
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: gamevault
docker_project_src: /opt/gamevault
