# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: alora
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID9QCtIydZUojoI4XxLVE6FCTyIq+xXZomQG5BE15lEE alora@finance.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Alora] Firefly/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Alora] Firefly/user.keytab"

# NFS
nfs_user_name: firefly
nfs_user_id: 160
nfs_mounts:
  alora:
    mount_share: alora
    mount_point: /srv/alora

## NGINX variables
nginx_conf_files:
  - filename: firefly.conf
    path: templates/nginx.firefly.conf

## Firefly variables
firefly_docker_name: firefly

## Docker variables
docker_project_name: firefly
docker_project_src: /opt/firefly
