# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.17.1

# User
debian_user_name: sapphire
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILFCrnhoRXArmOU1CMBUdq1S3GyqXvxpG+mnSZ50p2W6 sapphire@tv.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Sapphire] Sonarr/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Sapphire] Sonarr/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['sonarr'].name }}"
nfs_user_id: "{{ nfs_clients['sonarr'].uid }}"
nfs_mounts:
  marilyn:
    mount_share: /marilyn
    mount_point: /srv/marilyn

## NGINX variables
nginx_conf_files:
  - filename: sonarr.conf
    path: templates/nginx.sonarr.conf
  - filename: sonarr4k.conf
    path: templates/nginx.sonarr4k.conf
  - filename: sonarr-anime.conf
    path: templates/nginx.sonarr-anime.conf

## Sonarr variables
sonarr_4k_hostname: tv4k.tinynamoo.com
sonarr_anime_hostname: animetv.tinynamoo.com
sonarr_media_group_name: media
sonarr_media_group_gid: "{{ nfs_groups['media'].gid }}"

sonarr_docker_name: sonarr

## Proxmox variables
proxmox_snapshot_vmid: 17113
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: sonarr
docker_project_src: /opt/sonarr
