# @format

# Arkenfox
# Update arkenfox on installed systems
---
- name: Update Arkenfox on all Firefox profiles that have it installed.
  hosts: arkenfox

  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"

  roles:
    - arkenfox
