# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1
debian_datetime_timezone: Asia/Singapore
debian_datetime_hardware_clock: UTC

# User
debian_user_name: sakura
debian_user_shell: /bin/bash
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMAVgcaHWq+24aLg0KijJ+/5AWqc1eJd6gypW9shHQR sakura@games.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_realm: TINYNAMOO.COM
nfs_krb5_kdc: storage.tinynamoo.com
nfs_krb5_admin_server: storage.tinynamoo.com
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Sakura] Gamevault/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Sakura] Gamevault/user.keytab"

# NFS
nfs_user_name: gamevault
nfs_user_id: 230
nfs_mount_server: storage.tinynamoo.
nfs_mounts:
  sakura:
    mount_share: sakura
    mount_point: /srv/sakura

## NGINX variables
nginx_conf_files:
  - filename: gamevault.conf
    path: templates/nginx.gamevault.conf

certbot_admin_email: admin@tinynamoo.com
