# @format

# Gamevault
# Configure & manage Gamevault games management server
---
- name: Configure & manage Gamevault games management server
  hosts: gamevault

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        task_list:
          - docker

  tasks:
    - name: Install and configure Gamevault games management server
      ansible.builtin.import_tasks: install.yaml
      tags: install
