# @format

# IT-Tools
# Install and configure IT-Tools developers tools collection.
---
- name: Create application directory
  become: true
  ansible.builtin.file:
    path: /opt/it-tools
    owner: "{{ debian_user_name }}"
    group: "{{ debian_user_name }}"
    mode: "0640"
    state: directory

- name: Setup IT-Tools docker compose file
  become: true
  ansible.builtin.copy:
    src: files/docker-compose.yaml
    dest: /opt/it-tools/docker-compose.yaml
    owner: "{{ debian_user_name }}"
    group: "{{ debian_user_name }}"
    mode: "0640"

- name: Install and configure nginx
  vars:
    task_list:
      - nginx
    nginx_tls_domains:
      - "{{ inventory_hostname }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start IT-Tools docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: it-tools
    project_src: /opt/it-tools
    state: present
