# @format

# Scrutiny
# Backup the Scrutiny sqlite database.
---
- name: Backup scrutiny sqlite database
  become: true
  block:
    - name: Ensure rsync is installed
      ansible.builtin.apt:
        name: rsync
        update_cache: true
        state: present

    - name: Ensure scrutiny docker containers are stopped
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: absent

    - name: Sync sqlite database from local application directory to NFS server
      ansible.posix.synchronize:
        src: "{{ docker_project_src }}/config/scrutiny.db"
        dest: "{{ nfs_mounts.solar.mount_point }}/scrutiny/config/"
        owner: false
        group: false
      delegate_to: "{{ inventory_hostname }}"

    - name: Start scrutiny docker containers
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: present
