# @format

# Wikijs
# Install and configure Wikijs wiki server.
---
- name: Setup Wikijs application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

    - name: Ensure git directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}/git"
        owner: "{{ nfs_user_id }}"
        group: "{{ nfs_user_id }}"
        mode: "0750"
        state: directory

    - name: Ensure ssh directory is present
      ansible.builtin.file:
        path: /home/{{ nfs_user_name }}/.ssh
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Copy SSH private key for gitea backup
      ansible.builtin.copy:
        src: "{{ wikijs_gitea_private_key_file }}"
        dest: /home/{{ nfs_user_name }}/.ssh/id_ed25519
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0600"

- name: Install and configure nginx
  vars:
    task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start wikijs docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
