# @format
---
## Proxmox variables
proxmox_vmid: 17113

proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: sonarr
docker_project_src: /opt/sonarr
