# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.14.1

# User
debian_user_name: wendy
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOap5QSvaoLanWbb/HtkCZCrsUc5V4AX/0fzat6MtoNP wendy@cloud.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Wendy] Nextcloud/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Wendy] Nextcloud/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['nextcloud'].name }}"
nfs_user_id: "{{ nfs_clients['nextcloud'].uid }}"
nfs_mounts:
  wendy:
    mount_share: /wendy
    mount_point: /srv/wendy

## NGINX variables
nginx_user: nextcloud
nginx_group: nextcloud
nginx_conf_files:
  - filename: nextcloud.conf
    path: templates/nginx.nextcloud.conf
  - filename: collabora.conf
    path: templates/nginx.collabora.conf

## Nextcloud variables
nextcloud_smtp_host: smtp.protonmail.ch
nextcloud_smtp_port: "587"
nextcloud_smtp_secure: tls
nextcloud_smtp_auth: LOGIN
nextcloud_smtp_from_address: sunny@mail.tinynamoo.com
nextcloud_smtp_mail_domain: tinynamoo.com

nextcloud_collabora_hostname: office.tinynamoo.com

nextcloud_docker_name: nextcloud
nextcloud_image_version: v2025.7.1

## Proxmox instance variables
proxmox_snapshot_vmid: 14100
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: nextcloud
docker_project_src: /opt/nextcloud
