# @format
---
## Debian-13-setup variables
# Datetime
debian_datetime_timezone: Asia/Singapore
debian_datetime_hardware_clock: UTC

# User
debian_user_shell: /bin/bash

# Miscellaneous
debian_architecture:
  {
    "armv6l": "armhf",
    "armv7l": "armhf",
    "aarch64": "arm64",
    "x86_64": "amd64",
    "i386": "i386",
  }
