# @format

# Uptime Kuma
# Backup the Uptime kuma data directory.
---
- name: Backup uptime kuma data directory
  become: true
  block:
    - name: Ensure rsync is installed
      ansible.builtin.apt:
        name: rsync
        update_cache: true
        state: present

    - name: Ensure uptime kuma docker containers are stopped
      community.docker.docker_compose_v2:
        project_name: uptime-kuma
        project_src: /opt/uptime-kuma
        state: absent

    - name: Sync data directory from local application directory to NFS server
      ansible.posix.synchronize:
        src: /opt/uptime-kuma/data
        dest: "{{ nfs_mounts.serene.mount_point }}/"
        owner: false
        group: false
      delegate_to: "{{ inventory_hostname }}"

    - name: Start uptime kuma docker containers
      community.docker.docker_compose_v2:
        project_name: uptime-kuma
        project_src: /opt/uptime-kuma
        state: present
