# @format

# Uptime Kuma
# Install and configure Uptime Kuma monitoring tool.
---
- name: Install and configure Uptime Kuma monitoring tool
  hosts: uptime_kuma

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        debian_common_task_list:
          - docker

  tasks:
    - name: Backup Uptime Kuma data directory
      ansible.builtin.import_tasks: backup.yaml
      tags: backup

    - name: Install and configure Uptime Kuma monitoring tool
      ansible.builtin.import_tasks: install.yaml
      tags: install
