# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: alyssa
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIvqIroYxmHf2FlFtDBRACUkmCT+LfU774UA7+D37Xf3 alyssa@archive.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Alyssa] Paperless/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Alyssa] Paperless/user.keytab"

# NFS
nfs_user_name: paperless
nfs_user_id: 130
nfs_mounts:
  alyssa:
    mount_share: alyssa
    mount_point: /srv/alyssa

## NGINX variables
nginx_conf_files:
  - filename: paperless.conf
    path: templates/nginx.paperless.conf

## Paperless variables
paperless_docker_name: paperless
gotenberg_docker_name: gotenberg

## Proxmox variables
proxmox_snapshot_vmid: 20130
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: paperless
docker_project_src: /opt/paperless
