# @format
---
# Date time configurations
debian_datetime_ntp_server: pool.ntp.org
debian_datetime_timezone: Asia/Singapore
debian_datetime_hardware_clock: UTC

# User configurations
debian_user_name: debian
debian_user_password: "*" # Hashed value - Use `mkpasswd -m SHA-512` to generate (`*` locks the password)
debian_user_shell: /bin/bash
debian_user_ssh_public_key: ""
