# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1
debian_datetime_timezone: Asia/Singapore
debian_datetime_hardware_clock: UTC

# User
debian_user_name: alyssa
debian_user_shell: /bin/bash
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIvqIroYxmHf2FlFtDBRACUkmCT+LfU774UA7+D37Xf3 alyssa@archive.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_realm: TINYNAMOO.COM
nfs_krb5_kdc: storage.tinynamoo.com
nfs_krb5_admin_server: storage.tinynamoo.com
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Alyssa] Paperless/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Alyssa] Paperless/user.keytab"

# NFS
nfs_user_name: paperless
nfs_user_id: 130
nfs_mount_server: storage.tinynamoo.com
nfs_mounts:
  alyssa:
    mount_share: alyssa
    mount_point: /srv/alyssa

## NGINX variables
nginx_conf_files:
  - filename: paperless.conf
    path: templates/nginx.paperless.conf

certbot_admin_email: admin@tinynamoo.com
