# @format

# Paperless
# Get current and latest versions of the paperless/gotenberg applications
---
- name: Get application current and latest versions
  block:
    - name: Get current {{ item.docker_name }} docker container version
      become: true
      ansible.builtin.import_role:
        name: docker
        public: false
      vars:
        task_list: get_container_image_version
        docker_container_name: "{{ item.docker_name }}"
        docker_fact_name: "{{ item.name }}"

    - name: Get latest {{ item.name }} release from github
      community.general.github_release:
        user: "{{ item.docker_user }}"
        repo: "{{ item.docker_repo }}"
        action: latest_release
      delegate_to: localhost
      register: github_release

    - name: Extract latest containers versions
      ansible.builtin.set_fact:
        "{{ item.name }}_latest_version": "{{ github_release.tag }}"
