# @format

# Paperless-ngx
# Install and configure the paperless-ngx documents management server.
---
- name: Setup Paperless-ngx application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: /opt/paperless
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: /opt/paperless/docker-compose.yaml
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

    - name: Setup paperless environment variables
      ansible.builtin.template:
        src: templates/app.environment.env
        dest: /opt/paperless/paperless.env
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

- name: Install and configure nginx
  vars:
    task_list:
      - nginx
    nginx_tls_domains:
      - "{{ inventory_hostname }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start paperless docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: paperless
    project_src: /opt/paperless
    state: present
