# @format

# Paperless-ngx
# Configure & manage Paperless-ngx documents management server.
---
- name: Configure & manage Paperless-ngx documents management server
  hosts: paperless

  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"
        - "{{ playbook_dir }}/credentials.yaml"
      tags: always

    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        task_list:
          - docker

  tasks:
    - name: Install and configure the Paperless-ngx documents management server
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade the Paperless-ngx documents management server
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
