# @format

# Proton Bridge Relay
# Manage the Proton Bridge relay.
---
- name: Install and configure the Proton Bridge relay
  hosts: proton_bridge_relay

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
          - architecture
      tags: install

  roles:
    - role: debian-13-setup
      tags: install

  tasks:
    - name: Install and configure the Proton Bridge relay
      ansible.builtin.import_tasks: install.yaml
      tags: install
