services:
  server:
    container_name: your_spotify_api
    image: yooooomi/your_spotify_server:latest
    environment:
      API_ENDPOINT: https://{{ yourspotify_api_hostname }}
      CLIENT_ENDPOINT: https://{{ inventory_hostname }}
      SPOTIFY_PUBLIC: {{ yourspotify_public_token }}
      SPOTIFY_SECRET: {{ yourspotify_private_secret }}
      MONGO_ENDPOINT: mongodb://mongodb:27017/your_spotify
      TIMEZONE: Asia/Singapore
      CORS: https://{{ inventory_hostname }}
    ports:
      - "8080:8080"
    restart: unless-stopped
    links:
      - mongodb
    depends_on:
      - mongodb
    user: {{ nfs_user_id }}:{{ nfs_user_id }}

  web:
    container_name: your_spotify_web
    image: yooooomi/your_spotify_client
    environment:
      API_ENDPOINT: https://{{ yourspotify_api_hostname }}
    ports:
      - "3000:3000"
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo:6
    volumes:
      - {{ nfs_mounts.melodee.mount_point }}/your_spotify_db:/data/db
    restart: unless-stopped
    user: {{ nfs_user_id }}:{{ nfs_user_id }}
