# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: False
  cross_seed: False
  recheck: True
  cat_update: False
  tag_update: True
  rem_unregistered: True
  tag_tracker_error: True
  rem_orphaned: True
  tag_nohardlinks: True
  share_limits: True
  skip_qb_version_check: False
  skip_cleanup: False

qbt:
  # qBittorrent parameters
  host: "qbittorrent:8080"
  user: "admin"
  pass: "{{ cross_seed_qbit_password }}"

settings:
  force_auto_tmm: False # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  force_auto_tmm_ignore_tags: [] # Torrents with these tags will be ignored when force_auto_tmm is enabled.
  tracker_error_tag: issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  share_limits_tag: ~share_limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached # Tag to be added to torrents that have not yet reached the minimum seeding time
  share_limits_min_num_seeds_tag: MinSeedsNotMet # Tag to be added to torrents that have not yet reached the minimum number of seeds
  share_limits_last_active_tag: LastActiveLimitNotReached # Tag to be added to torrents that have not yet reached the last active limit
  disable_qbt_default_share_limits: true # When running --share-limits function, it allows QBM to handle share limits by disabling qBittorrents default Share limits
  cross_seed_tag: cross-seed # Will set the tag of any torrents that are added by cross-seed command
  cat_filter_completed: True # Filters for completed torrents only when running cat_update command
  share_limits_filter_completed: True # Filters for completed torrents only when running share_limits command
  tag_nohardlinks_filter_completed: True # Filters for completed torrents only when running tag_nohardlinks command
  cat_update_all: True # Checks and udpates all torrent categories if set to True when running cat_update command, otherwise only update torrents that are uncategorized

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # remote_dir must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # remote_dir should not be set if qbit_manage is running in a container
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  # <OPTIONAL> orphaned_dir var: </your/path/here/>  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  cross_seed:
  root_dir: "/data/torrents/"
  remote_dir: "/data/torrents/"
  recycle_bin: "/data/torrents/.RecycleBin"
  torrents_dir: "/qbittorrent/BT_backup"
  orphaned_dir: "/data/torrents/orphaned_data"

cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  anime: "/data/torrents/anime"
  anime-completed: "/data/torrents/anime"
  anime-completed.cross-seed: "/data/torrents/anime"
  animetv: "/data/torrents/animetv"
  animetv-completed: "/data/torrents/animetv"
  animetv-completed.cross-seed: "/data/torrents/animetv"
  games: "/data/torrents/games"
  manual-seed: "/data/torrents/manual-seed"
  movies: "/data/torrents/movies"
  movies-completed: "/data/torrents/movies"
  movies-completed.cross-seed: "/data/torrents/movies"
  movies4k: "/data/torrents/movies4k"
  movies4k-completed: "/data/torrents/movies4k"
  movies4k-completed.cross-seed: "/data/torrents/movies4k"
  prowlarr: "/data/torrents/prowlarr"
  tv: "/data/torrents/tv"
  tv-completed: "/data/torrents/tv"
  tv-completed.cross-seed: "/data/torrents/tv"
  tv4k: "/data/torrents/tv4k"
  tv4k-completed: "/data/torrents/tv4k"
  tv4k-completed.cross-seed: "/data/torrents/tv4k"

  cross-seed-link: "/data/media/cross-seed-links/*"

cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>


tracker:
  # Mandatory
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url. You can define multiple tracker urls by splitting with `|` delimiter
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Set the category based on tracker URL. This category option takes priority over the category defined by save directory
  #   cat: <Category Name>
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  1337x:
    tag:
      - 1337x
  aither:
    tag:
    - aither
  animetorrents:
    tag:
    - animetorrents
  avistaz:
    tag:
      - avistaz
  blutopia:
    tag:
      - blutopia
  cinemaz:
    tag:
      - cinemaz
  digitalcore:
    tag:
      - digitalcore
  filelist:
    tag:
      - filelist
  hawke.uno:
    tag:
      - hawke-uno
  hd-space:
    tag:
      - hd-space
  lst:
    tag:
      - lst
  privatehd:
    tag:
      - privatehd
  milkie:
    tag:
      - milkie
  nyaa:
    tag:
      - nyaa
  oldtoons:
    tag:
      - oldtoons
  torrentleech:
    tag:
      - torrentleech
  upload.cx:
    tag:
      - upload.cx
  # The "other" key is a special keyword and if defined will tag any other trackers that don't match the above trackers into this tag
  other:
    tag: other

nohardlinks:
  # Tag Movies/Series that are not hard linked outside the root directory
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
  movies-completed:
  movies4k-completed:
  tv-completed:
  tv4k-completed:

share_limits:
  # Control how torrent share limits are set depending on the priority of your grouping
  # Each torrent will be matched with the share limit group with the highest priority that meets the group filter criteria.
  # Each torrent can only be matched with one share limit group
  # This variable is mandatory and is a text defining the name of your grouping. This can be any string you want
  noHL:
    priority: 1
    include_all_tags:
      - noHL
    include_any_tags:
      - noHL
    max_ratio: 0
    max_seeding_time: 0
    cleanup: true
    add_group_to_tag: true
    min_num_seeds: 0
  cross-seed:
    priority: 2
    include_all_tags:
      - cross-seed
    categories:
      - cross-seed-link
      - anime-completed.cross-seed
      - animetv-completed.cross-seed
      - movies-completed.cross-seed
      - movies4k-completed.cross-seed
      - tv-completed.cross-seed
      - tv4k-completed.cross-seed
    max_ratio: 10.0
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  avistaz:
    priority: 3
    include_all_tags:
      - avistaz
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 6mo
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 5
    cleanup: true
  cinemaz:
    priority: 4
    include_all_tags:
      - cinemaz
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 6mo
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 5
    cleanup: true
  hd-space:
    priority: 5
    include_all_tags:
      - hd-space
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    cleanup: true
  oldtoons:
    priority: 6
    include_all_tags:
      - oldtoons
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  upload.cx:
    priority: 7
    include_all_tags:
      - upload.cx
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  milkie:
    priority: 8
    include_all_tags:
      - milkie
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 1
    max_seeding_time: 30d
    cleanup: true
  lst:
    priority: 10
    include_all_tags:
      - lst
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 10d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  nyaa:
    priority: 11
    include_all_tags:
      - nyaa
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 0
    max_seeding_time: 30d
    cleanup: true
  digitalcore:
    priority: 12
    include_all_tags:
      - digitalcore
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 5d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  aither:
    priority: 13
    include_all_tags:
      - aither
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 10d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  hawke-uno:
    priority: 14
    include_all_tags:
      - hawke-uno
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 5d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  torrentleech:
    priority: 15
    include_all_tags:
      - torrentleech
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 10d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  privatehd:
    priority: 16
    include_all_tags:
      - privatehd
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 20d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 5
    cleanup: true
  blutopia:
    priority: 17
    include_all_tags:
      - blutopia
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  animetorrents:
    priority: 18
    include_all_tags:
      - animetorrents
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  filelist:
    priority: 19
    include_all_tags:
      - filelist
    categories:
      - anime
      - animetv
      - movies
      - movies4k
      - tv
      - tv4k
      - anime-completed
      - animetv-completed
      - movies-completed
      - movies4k-completed
      - tv-completed
      - tv4k-completed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  manual-seed:
    priority: 100
    categories:
      - manual-seed
    max_ratio: 10.0
    min_seeding_time: 7d
    max_seeding_time: 1y
    last_active: 7d
    min_num_seeds: 1
    cleanup: true
  default:
    priority: 999
    max_ratio: -1
    max_seeding_time: -1
    cleanup: true

recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  empty_after_x_days: 30
  save_torrents: true
  split_by_category: false

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  empty_after_x_days: 30
  exclude_patterns:
    - "**/.DS_Store"
    - "**/Thumbs.db"
    - "**/@eaDir"
    - "/data/torrents/temp/**"
    - "**/*.!qB"
    - "**/*_unpackerred"
  max_orphaned_files_to_delete: 50

# apprise:
  # Apprise integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out the url of your apprise API endpoint
  # api_url:
  # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  # notify_url:

# notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  # apikey: ####################################
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  # instance:

# webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Set value to nothing (leave Empty/Blank) to disable
  # error:
  # run_start:
  # run_end:
  # function:
  #   cross_seed:
  #   recheck:
  #   cat_update:
  #   tag_update:
  #   rem_unregistered:
  #   tag_tracker_error:
  #   rem_orphaned:
  #   tag_nohardlinks:
  #   share_limits:
  #   cleanup_dirs:
