# @format

# Jellyfin
# Backup the Jellyfin data directory.
---
- name: Backup Jellyfin data directory
  become: true
  block:
    - name: Ensure rsync is installed
      ansible.builtin.apt:
        name: rsync
        update_cache: true
        state: present

    - name: Ensure jellyfin docker containers are stopped
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: absent

    - name: Sync data directory from local application directory to NFS server
      ansible.posix.synchronize:
        src: "{{ docker_project_src }}/data/"
        dest: '{{ nfs_mounts["marilyn-configs-jellyfin"].mount_point }}/data/jellyfin'
        owner: false
        group: false
      delegate_to: "{{ inventory_hostname }}"

    - name: Start jellyfin docker containers
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        state: present
      when: "'backup' in ansible_run_tags"
