# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.10.1

# User
debian_user_name: solar
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBsZq3Eceg8RrDTyoh7iqVwKSfLf7FwU6sOljydwMHjK solar@smart.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Solar] Scrutiny/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Solar] Scrutiny/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['scrutiny'].name }}"
nfs_user_id: "{{ nfs_clients['scrutiny'].uid }}"
nfs_mounts:
  solar:
    mount_share: /solar
    mount_point: /srv/solar

## NGINX variables
nginx_conf_files:
  - filename: scrutiny.conf
    path: templates/nginx.scrutiny.conf

## Scrutiny variables
scrutiny_smtp_hostname: smtp.tinynamoo.com
scrutiny_smtp_from_email: sunny@mail.tinynamoo.com
scrutiny_smtp_to_email: admin@tinynamoo.com

scrutiny_ntfy_hostname: push.tinynamoo.com
scrutiny_ntfy_topic: Scrutiny

scrutiny_docker_name: scrutiny

## Docker variables
docker_project_name: scrutiny
docker_project_src: /opt/scrutiny

## Proxmox variables
proxmox_snapshot_vmid: 10150
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false
