# @format
---
- name: Restart docker daemon
  become: true
  ansible.builtin.systemd_service:
    name: docker.service
    daemon_reload: true
    state: restarted

- name: Reload nginx configuration
  become: true
  ansible.builtin.command: nginx -s reload
  changed_when: true
