# @format
---
- name: Ensure systemd-timesyncd is installed
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present
  become: true

- name: "Set timezone to {{ debian_datetime_timezone }}"
  community.general.timezone:
    hwclock: "{{ debian_datetime_hardware_clock }}"
    name: "{{ debian_datetime_timezone }}"
  notify: Restart timesyncd
  become: true

- name: Setup time synchronisation
  ansible.builtin.template:
    src: templates/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
  notify: Restart timesyncd
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure apt uses https sources
  ansible.builtin.copy:
    src: files/debian-apt-sources.list
    dest: /etc/apt/sources.list
    mode: "0644"
  notify: Update apt cache
  become: true

- name: Update apt cache, upgrade packages and remove unused dependencies
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    purge: true
  become: true

- name: Harden SSH server
  ansible.builtin.copy:
    src: files/ssh_hardening.conf
    dest: /etc/ssh/sshd_config.d/ssh_hardening.conf
    mode: "0644"
  notify: Restart ssh
  become: true

- name: Ensure unattended-upgrades is installed
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  become: true
