# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: stevie
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvay5tAPN1ExeoASzXSZiLuRGXmSMrcuLnvI9DOu7U8 stevie@send.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Stevie] Send/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Stevie] Send/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['send'].name }}"
nfs_user_id: "{{ nfs_clients['send'].uid }}"
nfs_mounts:
  stevie:
    mount_share: /stevie
    mount_point: /srv/stevie

## NGINX variables
nginx_conf_files:
  - filename: send.conf
    path: templates/nginx.send.conf

send_docker_name: send

## Docker variables
docker_project_name: send
docker_project_src: /opt/send
