# @format

# Prowlarr
# Install and configure the Prowlarr indexers managment server.
---
- name: Setup Prowlarr application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: /opt/prowlarr
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: /opt/prowlarr/docker-compose.yaml
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

- name: Setup prowlarr user
  become: true
  block:
    - name: Create media group
      ansible.builtin.group:
        name: "{{ prowlarr_media_group_name }}"
        gid: "{{ prowlarr_media_group_gid }}"
        system: true
        state: present

    - name: Add prowlarr user to media group
      ansible.builtin.user:
        name: "{{ nfs_user_name }}"
        groups: "{{ prowlarr_media_group_name }}"
        append: true

- name: Install and configure nginx
  vars:
    task_list:
      - nginx
    nginx_tls_domains:
      - "{{ inventory_hostname }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start prowlarr docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: prowlarr
    project_src: /opt/prowlarr
    state: present
