# @format

# Prowlarr
# Configure & manage Prowlarr indexer management server.
---
- name: Configure & manage Prowlarr indexer management server
  hosts: prowlarr

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-13-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        debian_common_task_list:
          - docker

  tasks:
    - name: Install and configure the Prowlarr indexer managment server
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade Prowlarr indexer managment server
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
