# @format

# Prowlarr
# Upgrade Prowlarr indexer managment server
---
- name: Check if prowlarr requires update
  become: true
  block:
    - name: Get current prowlarr container version
      ansible.builtin.import_role:
        name: docker
        public: false
      vars:
        docker_task_list: get_container_image_version
        docker_container_name: "{{ prowlarr_docker_name }}"
        docker_fact_name: prowlarr

    - name: Get latest prowlarr container release from github
      become: false
      community.general.github_release:
        user: linuxserver
        repo: docker-prowlarr
        action: latest_release
      delegate_to: localhost
      register: prowlarr_github_release

    - name: Extract latest prowlarr container version
      ansible.builtin.set_fact:
        prowlarr_latest_version: "{{ prowlarr_github_release.tag }}"

    - name: Stop play if prowlarr has no updates
      ansible.builtin.meta: end_play
      when: prowlarr_image_version == prowlarr_latest_version

- name: Take snapshot of Proxmox instance
  ansible.builtin.import_role:
    name: proxmox
    public: false
  vars:
    proxmox_task_list: snapshot
    proxmox_snapshot_name: "{{ 'pre_upgrade_' + (prowlarr_image_version | regex_replace('[.]', '-')) }}"
    proxmox_snapshot_description: "[Ansible] Working snapshot of prowlarr {{ prowlarr_image_version }} before upgrading to {{ prowlarr_latest_version }}"
  delegate_to: localhost

- name: Upgrade Prowlarr indexer managment server
  become: true
  block:
    - name: Update apt cache, upgrade packages and remove unused dependencies
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        purge: true

    - name: Update & start Prowlarr docker containers
      become: true
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        remove_orphans: true
        pull: always
        state: present

    - name: Prune unused docker objects
      community.docker.docker_prune:
        builder_cache_all: true
        containers: true
        images: true
        networks: true
        volumes: true
