# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: yena
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJMPB95ATnnMKunX74CtylHzGFDUevE4J+1RCsAqwZwQ yena@git.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Yena] Gitea/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Yena] Gitea/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['gitea'].name }}"
nfs_user_id: "{{ nfs_clients['gitea'].uid }}"
nfs_user_shell: /bin/bash
nfs_mounts:
  yena:
    mount_share: /yena
    mount_point: /srv/yena

## NGINX variables
nginx_conf_files:
  - filename: gitea.conf
    path: templates/nginx.gitea.conf

## Gitea configurations
gitea_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIxW2NoBiOA/73caeYjYLvHpId88UOdJtERcz+d/r4S0 Gitea Host Key"

gitea_docker_name: gitea
gitea_image_version: v1.25.0

gitea_smtp_host: smtp.protonmail.ch
gitea_smtp_port: 587
gitea_smtp_protocol: smtp+starttls
gitea_smtp_from_address: sunny@mail.tinynamoo.com

## Proxmox variables
proxmox_snapshot_vmid: 20180
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: gitea
docker_project_src: /opt/gitea
