# @format
---
- name: Reinstall proxmox-widget toolkit # noqa: command-instead-of-module command-instead-of-shell
  ansible.builtin.shell:
    cmd: apt-get --reinstall install proxmox-widget-toolkit
  environment:
    DEBIAN_FRONTEND: noninteractive
  changed_when: true

- name: Reload network configuration # noqa: no-handler
  ansible.builtin.command: ifreload -a
  changed_when: true
  when: network_interfaces.changed
