# @format

# Debian
# Configure & manage Debian servers.
---
- name: Configure & manage Debian servers
  hosts: debian

  tasks:
    - name: Upgrade packages & purge unused dependencies
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        purge: true
      tags: upgrade

    - name: Install and setup debian base configurations
      ansible.builtin.import_role:
        name: debian-13-setup
      tags: install
