# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: winter
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK5P943ZRtRZc8vTe15cgSawyUbZZSUk4mb893WYUbiE winter@wiki.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Winter] Wikijs/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Winter] Wikijs/user.keytab"

# NFS
nfs_user_name: wikijs
nfs_user_id: 170
nfs_mounts:
  winter:
    mount_share: winter
    mount_point: /srv/winter

## NGINX variables
nginx_conf_files:
  - filename: wikijs.conf
    path: templates/nginx.wikijs.conf

## Wikijs variables
wikijs_docker_name: wikijs

## Proxmox variables
proxmox_snapshot_vmid: 20170
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: wikijs
docker_project_src: /opt/wikijs
