# @format
---
- name: Restart timesyncd service
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    state: restarted
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Restart ssh service
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
