# @format

# Gitea
# Install and configure Gitea git server.
---
- name: Setup Gitea application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

- name: Setup gitea SSH container passthrough
  become: true
  block:
    - name: Copy gitea SSH public key to server
      ansible.posix.authorized_key:
        user: "{{ nfs_user_name }}"
        key: "{{ gitea_public_key }}"
        state: present

    - name: Ensure permissions of authorized keys is set correctly
      ansible.builtin.file:
        path: /home/{{ nfs_user_name }}/.ssh/authorized_keys
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0600"
        state: file

    - name: Copy gitea private key to server
      ansible.builtin.copy:
        src: "{{ gitea_private_key_file }}"
        dest: /home/{{ nfs_user_name }}/.ssh/id_ed25519
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0600"

    - name: Create fake host `gitea` command
      ansible.builtin.copy:
        src: files/app.gitea
        dest: /usr/local/bin/gitea
        owner: root
        group: root
        mode: "0755"

- name: Setup Fail2Ban
  become: true
  block:
    - name: Install Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        update_cache: true
        state: present

    - name: Add gitea fail2ban filter
      ansible.builtin.template:
        src: templates/fail2ban.filter.gitea.conf
        dest: /etc/fail2ban/filter.d/gitea.conf
        owner: root
        group: root
        mode: "0644"

    - name: Add gitea fail2ban jail
      ansible.builtin.template:
        src: templates/fail2ban.jail.gitea.conf
        dest: /etc/fail2ban/jail.d/gitea.conf
        owner: root
        group: root
        mode: "0644"

    - name: Add gitea docker fail2ban jail
      ansible.builtin.template:
        src: templates/fail2ban.jail.gitea-docker.conf
        dest: /etc/fail2ban/jail.d/gitea-docker.conf
        owner: root
        group: root
        mode: "0644"

    - name: Configure sshd jail (addresses upstream bug)
      ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.conf
        line: "backend = systemd"
        regexp: "^backend = .*sshd.*"
        state: present

    - name: Restart fail2ban
      ansible.builtin.systemd_service:
        name: fail2ban.service
        state: restarted

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start gitea docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
