---
services:
  drop:
    container_name: {{ drop_docker_name }}
    image: ghcr.io/drop-oss/drop:latest
    environment:
      DATABASE_URL: postgres://drop:{{ drop_database_password }}@postgres:5432/drop
      EXTERNAL_URL: https://{{ ansible_host }}
      IGDB_CLIENT_ID: {{ drop_igdb_client_id }}
      IGDB_CLIENT_SECRET: {{ drop_igdb_client_secret }}
    volumes:
      # Folder where your games are stored
      - {{ nfs_mounts.daisy.mount_point }}/library:/library
      - {{ nfs_mounts.daisy.mount_point }}/data:/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: drop
      POSTGRES_PASSWORD: {{ drop_database_password }}
      POSTGRES_DB: drop
    volumes:
      - {{ nfs_mounts.daisy.mount_point }}/db:/var/lib/postgresql/data
    user: {{ nfs_user_id }}:{{ nfs_user_id }}
    restart: unless-stopped
    healthcheck:
      test: pg_isready -d drop -U drop
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
