# @format

global:
  # How frequently to scrape targets by default.
  scrape_interval: 1m

  # How long until a scrape request times out.
  # It cannot be greater than the scrape interval.
  scrape_timeout: 10s

  # How frequently to evaluate rules.
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    scheme: https
    static_configs:
      - targets: ["monitor.tinynamoo.com"]

  - job_name: "node-exporters"
    scheme: https
    static_configs:
      - targets: {{ groups['debian'] | difference(groups['ansible']) | map('extract', hostvars) | map(attribute='ansible_host') | product([':9110']) | map('join') | list }}
