# @format

# Proxmox
# Configure & manage the Proxmox hypervisor.
---
- name: Configure & manage the Proxmox hypervisor
  hosts: proxmox

  roles:
    - role: debian-12-setup
      tags: install

  tasks:
    - name: Install and configure the Proxmox hypervisor
      ansible.builtin.import_tasks: install.yaml
      tags: install
