# @format

# Proxmox
# Configure & manage the Proxmox hypervisor.
---
- name: Configure & manage the Proxmox hypervisor
  hosts: proxmox

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yaml

  tasks:
    - name: Install and configure the Proxmox hypervisor
      ansible.builtin.import_tasks: install.yaml
      tags: install
