# @format

# IT-Tools
# Install and configure IT-Tools developers tools collection.
---
- name: Install and configure IT-Tools developers tools collection
  hosts: it_tools

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-13-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        debian_common_task_list:
          - docker

  tasks:
    - name: Install and configure IT-Tools developers tools collection
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade IT-Tools developers tools collection
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
