# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1
debian_datetime_timezone: Asia/Singapore
debian_datetime_hardware_clock: UTC

# User
debian_user_name: dahlia
debian_user_shell: /bin/bash
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNZXj6RHh4KAAPaDW7SPWW6n9Xx4OYwE5boKGDBu/lV dahlia@download.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_realm: TINYNAMOO.COM
nfs_krb5_kdc: storage.tinynamoo.com
nfs_krb5_admin_server: storage.tinynamoo.com
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Dahlia] qBittorrent/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Dahlia] qBittorrent/user.keytab"

# NFS
nfs_user_name: qbit
nfs_user_id: 284
nfs_mount_server: storage.tinynamoo.com
nfs_mounts:
  marilyn:
    mount_share: marilyn
    mount_point: /srv/marilyn

## NGINX variables
nginx_conf_files:
  - filename: qbittorrent.conf
    path: templates/nginx.qbittorrent.conf

certbot_admin_email: admin@tinynamoo.com

## qBittorrent variables
qbit_media_group_name: media
qbit_media_group_gid: 200

protonvpn_gateway: 10.2.0.1
protonvpn_port_forward_lifetime: 60 # ProtonVPN currently limits at 60s
protonvpn_port_forward_interval: 45

cross_seed_prowlarr_hostname: indexers.tinynamoo.com
cross_seed_ntfy_hostname: push.tinynamoo.com
