# @format

# qBittorrent
# Get current and latest versions of the qBittorrent/cross-seed applications
---
- name: Get application current and latest versions
  block:
    - name: Get current docker container version - {{ item.docker_name }}
      become: true
      ansible.builtin.import_role:
        name: docker
        public: false
      vars:
        docker_task_list: get_container_image_version
        docker_container_name: "{{ item.docker_name }}"
        docker_fact_name: "{{ item.name }}"

    - name: Get latest release from github - {{ item.name }}
      community.general.github_release:
        user: "{{ item.docker_user }}"
        repo: "{{ item.docker_repo }}"
        action: latest_release
      delegate_to: localhost
      register: github_release

    - name: Extract latest containers versions
      ansible.builtin.set_fact:
        "{{ item.name }}_latest_version": "{{ github_release.tag }}" # noqa: var-naming[no-jinja]
