# @format

# qBittorrent
# Configure & manage qBittorrent downloads server.
---
- name: Configure & manage qBittorrent downloads server
  hosts: qbittorrent

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        task_list:
          - docker

  tasks:
    - name: Install and configure qBittorrent downloads server
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade qBittorrent downloads server
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
