# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.17.1

# User
debian_user_name: dahlia
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNZXj6RHh4KAAPaDW7SPWW6n9Xx4OYwE5boKGDBu/lV dahlia@download.tinynamoo.com"

# Node exporter
node_exporter_listen_ip: "{{ ansible_enp6s18.ipv4.address }}"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Dahlia] qBittorrent/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Dahlia] qBittorrent/user.keytab"

# NFS
nfs_user_name: "{{ nfs_clients['qbittorrent'].name }}"
nfs_user_id: "{{ nfs_clients['qbittorrent'].uid }}"
nfs_mounts:
  marilyn:
    mount_share: /marilyn
    mount_point: /srv/marilyn

## NGINX variables
nginx_conf_files:
  - filename: qbittorrent.conf
    path: templates/nginx.qbittorrent.conf

## qBittorrent variables
qbit_media_group_name: media
qbit_media_group_gid: "{{ nfs_groups['media'].gid }}"

qbittorrent_docker_name: qbittorrent
qbittorrent_docker_ip: 172.18.0.2

protonvpn_gateway: 10.2.0.1
protonvpn_port_forward_lifetime: 60 # ProtonVPN currently limits at 60s
protonvpn_port_forward_interval: 45

cross_seed_prowlarr_hostname: indexers.tinynamoo.com
cross_seed_sonarr_hostname: tv.tinynamoo.com
cross_seed_sonarr4k_hostname: tv4k.tinynamoo.com
cross_seed_sonarr_anime_hostname: animetv.tinynamoo.com
cross_seed_radarr_hostname: movies.tinynamoo.com
cross_seed_radarr4k_hostname: movies4k.tinynamoo.com
cross_seed_radarr_anime_hostname: anime.tinynamoo.com
cross_seed_ntfy_hostname: push.tinynamoo.com
cross_seed_docker_name: cross-seed

qbit_manage_docker_name: qbit-manage
qbit_manage_image_version: v4.6.2

## Proxmox variables
proxmox_snapshot_vmid: 17112
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: qbittorrent
docker_project_src: /opt/qbittorrent
