
---
services:
  gamevault:
    container_name: {{ gamevault_docker_name }}
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USERNAME: gamevault
      DB_PASSWORD: {{ gamevault_database_password }}

      # The following line grants Admin Role to the account with this username upon registration.
      SERVER_ADMIN_USERNAME: admin

      PUID: {{ nfs_user_id }}
      PGID: {{ nfs_user_id }}

      METADATA_IGDB_CLIENT_ID: {{ gamevault_igdb_client_id }}
      METADATA_IGDB_CLIENT_SECRET: {{ gamevault_igdb_client_secret }}
    volumes:
      # Mount the folder where your games are
      - {{ nfs_mounts.sakura.mount_point }}/gamevault/games:/files
      # Mount the folder where GameVault should store its media
      - {{ nfs_mounts.sakura.mount_point }}/gamevault/media:/media
      # Mount the folder where logs are stored
      - {{ nfs_mounts.sakura.mount_point }}/gamevault/logs:/logs
    ports:
      - 8080:8080
    user: {{ nfs_user_id }}:{{ nfs_user_id }}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: {{ gamevault_database_password }}
      POSTGRES_DB: gamevault
    volumes:
      # Mount the folder where your PostgreSQL database files should land
      - {{ nfs_mounts.sakura.mount_point }}/gamevault/database:/var/lib/postgresql/data
    user: {{ nfs_user_id }}:{{ nfs_user_id }}
