# @format
---
## Debian-12-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1
debian_datetime_timezone: Asia/Singapore
debian_datetime_hardware_clock: UTC

# User
debian_user_name: florence
debian_user_shell: /bin/bash
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAXAyyxa9wKW4ZfozxEk+A32+n4ZLv5QuT9FJvDJcutM florence@feed.tinynamoo.com"

## NFSv4-client-setup variables
# Kerberos
nfs_krb5_realm: TINYNAMOO.COM
nfs_krb5_kdc: storage.tinynamoo.com
nfs_krb5_admin_server: storage.tinynamoo.com
nfs_krb5_host_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Florence] Miniflux/host.keytab"
nfs_krb5_user_keytab_file: "/mnt/veracrypt2/Kerberos Keytabs/[Florence] Miniflux/user.keytab"

# NFS
nfs_user_name: miniflux
nfs_user_id: 250
nfs_mount_server: storage.tinynamoo.com
nfs_mounts:
  florence:
    mount_share: florence
    mount_point: /srv/florence

## NGINX variables
nginx_conf_files:
  - filename: miniflux.conf
    path: templates/nginx.miniflux.conf

certbot_admin_email: admin@tinynamoo.com
