# @format

# Miniflux
# Install and configure Miniflux feed reader.
---
- name: Install and configure Miniflux feed reader
  hosts: miniflux

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-13-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        debian_common_task_list:
          - docker

  tasks:
    - name: Install and configure Miniflux feed reader
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade Miniflux feed reader
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
