# @format

# Minflux
# Upgrade Miniflux feed reader
---
- name: Get latest miniflux container release from github
  become: false
  community.general.github_release:
    user: miniflux
    repo: v2
    action: latest_release
  delegate_to: localhost
  register: miniflux_github_release

- name: Extract latest radarr container version
  ansible.builtin.set_fact:
    miniflux_latest_version: "{{ miniflux_github_release.tag }}"

- name: Take snapshot of Proxmox instance
  ansible.builtin.import_role:
    name: proxmox
    public: false
  vars:
    proxmox_task_list: snapshot
    proxmox_snapshot_name: "{{ 'pre_upgrade_miniflux_' + (miniflux_latest_version | regex_replace('[.]', '-')) }}"
    proxmox_snapshot_description: "[Ansible] Working snapshot of miniflux before upgrading to {{ miniflux_latest_version }}"
  delegate_to: localhost

- name: Upgrade miniflux feed reader
  become: true
  block:
    - name: Update apt cache, upgrade packages and remove unused dependencies
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        purge: true

    - name: Update & start miniflux container
      become: true
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        remove_orphans: true
        pull: always
        state: present

    - name: Prune unused docker objects
      community.docker.docker_prune:
        builder_cache_all: true
        containers: true
        images: true
        networks: true
        volumes: true
