# @format
---
- name: Get {{ docker_container_name }} docker container information
  community.docker.docker_container_info:
    name: "{{ docker_container_name }}"
  register: docker_container

- name: Ensure {{ docker_container_name }} docker container is present
  ansible.builtin.assert:
    that: docker_container.exists
    fail_msg: "Docker container '{{ docker_container_name }}' does not exist"

- name: Extract {{ docker_container_name }} docker container image version
  ansible.builtin.set_fact:
    {
      "{{ docker_fact_name }}_image_version": "{{ docker_container.container.Config.Labels['org.opencontainers.image.version'] }}",
    }
