# @format
---
- name: Get docker container information
  community.docker.docker_container_info:
    name: "{{ docker_container_name }}"
  register: docker_container

- name: Ensure docker container is present
  ansible.builtin.assert:
    that: docker_container.exists
    fail_msg: "Docker container '{{ docker_container_name }}' does not exist"

- name: Extract docker container image version
  ansible.builtin.set_fact:
    docker_container_image_version: "{{ docker_container.container.Config.Labels['org.opencontainers.image.version'] }}"
