# @format

# Piped
# Configure & manage Piped youtube proxy server.
---
- name: Configure & manage Piped youtube proxy server
  hosts: piped

  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"
        - "{{ playbook_dir }}/credentials.yaml"
      tags: always

    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags:
        - install
        - default
    - role: nfsv4-client-setup
      tags:
        - install
        - default
    - role: debian-common
      vars:
        task_list:
          - docker
      tags:
        - install
        - default

  tasks:
    - name: Install and configure Piped youtube proxy server
      ansible.builtin.import_tasks: install.yaml
      tags:
        - install
        - default
