# @format
---
- name: Install docker engine
  become: true
  block:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - architecture
          - distribution_release

    - name: Ensure ca-certificates package is present
      ansible.builtin.apt:
        name:
          - ca-certificates
        update_cache: true
        state: present

    - name: Ensure apt keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: Add docker's official gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: "0644"

    - name: Add docker repository to apt sources
      ansible.builtin.template:
        src: templates/apt-docker.list
        dest: /etc/apt/sources.list.d/docker.list
        owner: root
        group: root
        mode: "0644"

    - name: Install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        state: present

# Docker changes the FORWARD policy to DROP which breaks networking on the vms
- name: Fix iptables issue introduced by docker to allow for VM networking to work
  become: true
  when: inventory_hostname == 'proxmox'
  block:
    - name: Ensure docker override directory is present
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: Setup docker service override
      ansible.builtin.template:
        src: templates/docker.iptables-override.conf
        dest: /etc/systemd/system/docker.service.d/iptables-override.conf
        owner: root
        group: root
        mode: "0644"

    - name: Restart docker daemon
      ansible.builtin.systemd_service:
        name: docker.service
        daemon_reload: true
        state: restarted
