# @format
---
- name: Install git
  ansible.builtin.include_tasks: git.yaml
  when: "'git' in debian_common_task_list"

- name: Install docker
  ansible.builtin.include_tasks: docker.yaml
  when: "'docker' in debian_common_task_list"

- name: Install and configure nginx
  ansible.builtin.include_tasks: nginx.yaml
  when: "'nginx' in debian_common_task_list"
