# @format
---
- name: Install git
  ansible.builtin.include_tasks: git.yaml
  when: "'git' in task_list"

- name: Install docker
  ansible.builtin.include_tasks: docker.yaml
  when: "'docker' in task_list"
