# @format

# Firefly III
# Install and configure the firefly iii finance management server.
---
- name: Setup Firefly III application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

    - name: Setup firefly environment variables
      ansible.builtin.template:
        src: templates/app.environment.env
        dest: "{{ docker_project_src }}/.env"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

    - name: Setup firefly locales
      ansible.builtin.template:
        src: files/app.locale.gen
        dest: "{{ docker_project_src }}/locale.gen"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0640"

    - name: Ensure rsync is installed
      ansible.builtin.apt:
        name: rsync
        update_cache: true
        state: present

    - name: Sync uploads directory from NFS server to local application directory
      ansible.posix.synchronize:
        src: "{{ nfs_mounts.alora.mount_point }}/uploads"
        dest: "{{ docker_project_src }}/"
      delegate_to: "{{ inventory_hostname }}"

    - name: Ensure uploads directory permissions is set
      ansible.builtin.file:
        path: "{{ docker_project_src }}/uploads"
        owner: "{{ nfs_user_name }}"
        group: "{{ nfs_user_name }}"
        mode: "0740"
        recurse: true
        follow: false
        state: directory

    - name: Setup rsync automated backup for firefly uploads directory
      block:
        - name: Setup automated monitoring of uploads directory
          ansible.builtin.template:
            src: templates/app.uploads-backup.path
            dest: /etc/systemd/system/firefly-uploads-backup.path
            owner: root
            group: root
            mode: "0644"

        - name: Setup rsync automated backup of uploads directory
          ansible.builtin.template:
            src: templates/app.uploads-backup.service
            dest: /etc/systemd/system/firefly-uploads-backup.service
            owner: root
            group: root
            mode: "0644"

        - name: Enable and start firefly uploads directory monitoring & backup
          ansible.builtin.systemd_service:
            name: firefly-uploads-backup.path
            daemon_reload: true
            enabled: true
            state: started

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start firefly docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
