# @format

# Firefly III
# Configure & manage Firefly III finance managment server.
---
- name: Configure & manage the Firefly III finance managment server
  hosts: firefly

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4
      tags: always

  roles:
    - role: debian-12-setup
      tags: install
    - role: nfsv4-client-setup
      tags: install
    - role: debian-common
      tags: install
      vars:
        debian_common_task_list:
          - docker

  tasks:
    - name: Install and configure the Firefly III finance manager server
      ansible.builtin.import_tasks: install.yaml
      tags: install

    - name: Upgrade the Firefly III finance manager server
      ansible.builtin.import_tasks: upgrade.yaml
      tags: upgrade
